remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Yongyan Deng
logo: /assets/img/profile.jpg
# description:
repo: https://github.com/YongyanDeng?tab=repositories
show_downloads: false
theme: jekyll-remote-theme
