remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: Yongyan Deng
logo: /assets/img/profile.jpg
description: Experienced Full Stack/Front-end Engineer with a strong focus on React.js and related technologies. Proficient in the full software development cycle, Agile, and Scrum. Skilled in HTML, CSS, React Bootstrap, Ant Design, and Material UI for responsive design, with backend knowledge in Node.js and various databases. Committed to writing clean, maintainable code and passionate about learning new technologies to enhance user experiences.
show_downloads: true
theme: jekyll-remote-theme
